name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          net user runneradmin Senha123!
          net localgroup administrators runneradmin /add
          echo "RDP configurado"
